language: java
dist: trusty

cache:
  directories:
    $HOME/.m2

env:
  - JAVA_TOOL_OPTIONS=-Dhttps.protocols=TLSv1.2

git:
  depth: 3

jobs:
  include:
    - &test
      stage: Test
      jdk: oraclejdk8
      install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Dgpg.skip=true -Ddependency-check.skip=true
      script:
        - mvn test -B -Ddependency-check.skip=true
    - <<: *test
      # Only the api and implementation need testing with Java 1.7
      jdk: oraclejdk7
      dist: precise
      install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Dgpg.skip=true -pl yoti-sdk-api,yoti-sdk-impl -Ddependency-check.skip=true
      script:
        - mvn test -B -pl yoti-sdk-api,yoti-sdk-impl -Ddependency-check.skip=true
    - <<: *test
      jdk: openjdk7
      dist: precise
      install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Dgpg.skip=true -pl yoti-sdk-api,yoti-sdk-impl -Ddependency-check.skip=true
      script:
        - mvn test -B -pl yoti-sdk-api,yoti-sdk-impl -Ddependency-check.skip=true
    - <<: *test
      jdk: openjdk8
    - <<: *test
      jdk: oraclejdk9
    - <<: *test
      jdk: openjdk9
    - <<: *test
      jdk: openjdk10
    - <<: *test
      jdk: openjdk11
    - <<: *test
      jdk: oraclejdk11
    - stage: Coverage
      name: Coveralls
      if: type = pull_request OR branch = master
      jdk: oraclejdk8
      install:
        - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Dgpg.skip=true -Ddependency-check.skip=true
      script:
        - mvn jacoco:prepare-agent test jacoco:report coveralls:report -pl yoti-sdk-impl
    - stage: Analysis
      name: Sonarcloud
      if: type = pull_request
      dist: trusty
      addons:
        sonarcloud:
          organization: "getyoti"
      install:
        - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Dgpg.skip=true -Ddependency-check.skip=true
      script:
        - mvn clean verify sonar:sonar -Ddependency-check.skip=true -Dgpg.skip=true -Dmaven.javadoc.skip=true


