version: 1
update_configs:
  - package_manager: "java:maven"
    directory: "/"
    update_schedule: "daily"
    target_branch: "DEVELOPMENT"

    default_reviewers:
      - "echarrod"
      - "davidgrayston"
      - "MrBurtyyy"

    default_assignees: ["MrBurtyyy"]
