name: Unit Test
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - 'master'
      - 'DEVELOPMENT*'

jobs:
  junit:
    name: Junit (Java ${{ matrix.jdk-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        jdk-version: [7,8,9,10,11]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Java ${{ matrix.jdk-version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk-version }}
          architecture: x64
      - run: mvn test -B -pl yoti-sdk-api -Ddependency-check.skip=true
